language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
# command to install dependencies
install: python setup.py install
# command to run tests
before_script:
  - pep8 --exclude=vendor --ignore=E501,E225 --max-line-length=160 .
#script:
  - nosetests%
